import React from 'react'


export const metadata = {
    title: 'Next.js',
    descript: 'Generated by Next.js'
}

export default function RootLayout({ children }: any) {
  return (
    <>
           { children }
    </>
 
  )
}
